# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgmanip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coco50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('split', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='coco50',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgmanip.Image1'),
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(to='imgmanip.Image1'),
        ),
    ]
