# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgmanip', '0002_auto_20171107_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
