# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('split', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(to='coco.Image'),
        ),
    ]
